/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testalimentacionsaludable;
import Clips.Coneccion;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.clipsrules.jni.CLIPSLoadException;
import net.sf.clipsrules.jni.*;
/**
 *
 * @author Charly
 */
public class Ventana extends javax.swing.JFrame {
    int r1,r2,r3,r4,r5,r6,r7,r8,r9,r10;
    CaptureRouter theRouter;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLSiempre1 = new javax.swing.JLabel();
        jLCasiSiempre1 = new javax.swing.JLabel();
        jLAVeces1 = new javax.swing.JLabel();
        jLCasiNunca1 = new javax.swing.JLabel();
        jLNunca1 = new javax.swing.JLabel();
        jRBSiempre1 = new javax.swing.JRadioButton();
        jRBCasiSiem1 = new javax.swing.JRadioButton();
        jRBAVeces1 = new javax.swing.JRadioButton();
        jRBCasiNunca = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLSiempre2 = new javax.swing.JLabel();
        jLCasiSiempre2 = new javax.swing.JLabel();
        jLAVeces2 = new javax.swing.JLabel();
        jLCasiNunca2 = new javax.swing.JLabel();
        jLNunca2 = new javax.swing.JLabel();
        jRBSiempre2 = new javax.swing.JRadioButton();
        jRBCasiSiem2 = new javax.swing.JRadioButton();
        jRBAVeces2 = new javax.swing.JRadioButton();
        jRBCasiNunca1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLSiempre3 = new javax.swing.JLabel();
        jLCasiSiempre3 = new javax.swing.JLabel();
        jLAVeces3 = new javax.swing.JLabel();
        jLCasiNunca3 = new javax.swing.JLabel();
        jLNunca3 = new javax.swing.JLabel();
        jRBSiempre3 = new javax.swing.JRadioButton();
        jRBCasiSiem3 = new javax.swing.JRadioButton();
        jRBAVeces3 = new javax.swing.JRadioButton();
        jRBCasiNunca2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLSiempre4 = new javax.swing.JLabel();
        jLCasiSiempre4 = new javax.swing.JLabel();
        jLAVeces4 = new javax.swing.JLabel();
        jLCasiNunca4 = new javax.swing.JLabel();
        jLNunca4 = new javax.swing.JLabel();
        jRBSiempre4 = new javax.swing.JRadioButton();
        jRBCasiSiem4 = new javax.swing.JRadioButton();
        jRBAVeces4 = new javax.swing.JRadioButton();
        jRBCasiNunca3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLSiempre5 = new javax.swing.JLabel();
        jLCasiSiempre5 = new javax.swing.JLabel();
        jLAVeces5 = new javax.swing.JLabel();
        jLCasiNunca5 = new javax.swing.JLabel();
        jLNunca5 = new javax.swing.JLabel();
        jRBSiempre5 = new javax.swing.JRadioButton();
        jRBCasiSiem5 = new javax.swing.JRadioButton();
        jRBAVeces5 = new javax.swing.JRadioButton();
        jRBCasiNunca4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLSiempre6 = new javax.swing.JLabel();
        jLCasiSiempre6 = new javax.swing.JLabel();
        jLAVeces6 = new javax.swing.JLabel();
        jLCasiNunca6 = new javax.swing.JLabel();
        jLNunca6 = new javax.swing.JLabel();
        jRBSiempre6 = new javax.swing.JRadioButton();
        jRBCasiSiem6 = new javax.swing.JRadioButton();
        jRBAVeces6 = new javax.swing.JRadioButton();
        jRBCasiNunca5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLSiempre7 = new javax.swing.JLabel();
        jLCasiSiempre7 = new javax.swing.JLabel();
        jLAVeces7 = new javax.swing.JLabel();
        jLCasiNunca7 = new javax.swing.JLabel();
        jLNunca7 = new javax.swing.JLabel();
        jRBSiempre7 = new javax.swing.JRadioButton();
        jRBCasiSiem7 = new javax.swing.JRadioButton();
        jRBAVeces7 = new javax.swing.JRadioButton();
        jRBCasiNunca6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLSiempre8 = new javax.swing.JLabel();
        jLCasiSiempre8 = new javax.swing.JLabel();
        jLAVeces8 = new javax.swing.JLabel();
        jLCasiNunca8 = new javax.swing.JLabel();
        jLNunca8 = new javax.swing.JLabel();
        jRBSiempre8 = new javax.swing.JRadioButton();
        jRBCasiSiem8 = new javax.swing.JRadioButton();
        jRBAVeces8 = new javax.swing.JRadioButton();
        jRBCasiNunca7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLSiempre9 = new javax.swing.JLabel();
        jLCasiSiempre9 = new javax.swing.JLabel();
        jLAVeces9 = new javax.swing.JLabel();
        jLCasiNunca9 = new javax.swing.JLabel();
        jLNunca9 = new javax.swing.JLabel();
        jRBSiempre9 = new javax.swing.JRadioButton();
        jRBCasiSiem9 = new javax.swing.JRadioButton();
        jRBAVeces9 = new javax.swing.JRadioButton();
        jRBCasiNunca8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLSiempre10 = new javax.swing.JLabel();
        jLCasiSiempre10 = new javax.swing.JLabel();
        jLAVeces10 = new javax.swing.JLabel();
        jLCasiNunca10 = new javax.swing.JLabel();
        jLNunca10 = new javax.swing.JLabel();
        jRBSiempre10 = new javax.swing.JRadioButton();
        jRBCasiSiem10 = new javax.swing.JRadioButton();
        jRBAVeces10 = new javax.swing.JRadioButton();
        jRBCasiNunca9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLRespuesta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("TEST DE ALIMENTACION SALUDABLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("1. Incluyo diariamente alimentos de todos los grupos (almidones, granos y cereales, frutas y vegetales, carnes,");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLSiempre1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre1.setText("Siempre");
        jPanel1.add(jLSiempre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLCasiSiempre1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre1.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLAVeces1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces1.setText("A veces");
        jPanel1.add(jLAVeces1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLCasiNunca1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca1.setText("Casi nunca");
        jPanel1.add(jLCasiNunca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLNunca1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca1.setText("Nunca");
        jPanel1.add(jLNunca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jRBSiempre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jRBCasiSiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jRBAVeces1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jRBCasiNunca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNuncaActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("2. Al preparar las comidas en casa se utilizan condimentos naturales como ajo, cebolla, culantro, perejil, cebollina, ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("orégano, ají, otros.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLSiempre2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre2.setText("Siempre");
        jPanel1.add(jLSiempre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLCasiSiempre2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre2.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLAVeces2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces2.setText("A veces");
        jPanel1.add(jLAVeces2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLCasiNunca2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca2.setText("Casi nunca");
        jPanel1.add(jLCasiNunca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLNunca2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca2.setText("Nunca");
        jPanel1.add(jLNunca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jRBSiempre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jRBCasiSiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jRBAVeces2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jRBCasiNunca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("3. Evito consumir alimentos con alto contenido de sal, con condimentos artificiales o empaquetados en sobre, latas,");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLSiempre3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre3.setText("Siempre");
        jPanel1.add(jLSiempre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLCasiSiempre3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre3.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLAVeces3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces3.setText("A veces");
        jPanel1.add(jLAVeces3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLCasiNunca3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca3.setText("Casi nunca");
        jPanel1.add(jLCasiNunca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLNunca3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca3.setText("Nunca");
        jPanel1.add(jLNunca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jRBSiempre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jRBCasiSiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jRBAVeces3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        jRBCasiNunca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("4. Evito consumir alimentos fritos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLSiempre4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre4.setText("Siempre");
        jPanel1.add(jLSiempre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLCasiSiempre4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre4.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLAVeces4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces4.setText("A veces");
        jPanel1.add(jLAVeces4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLCasiNunca4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca4.setText("Casi nunca");
        jPanel1.add(jLCasiNunca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jLNunca4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca4.setText("Nunca");
        jPanel1.add(jLNunca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jRBSiempre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jRBCasiSiem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jRBAVeces4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jRBCasiNunca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("5. Evito las sodas, te fríos y bebidas azucaradas.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLSiempre5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre5.setText("Siempre");
        jPanel1.add(jLSiempre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jLCasiSiempre5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre5.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLAVeces5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces5.setText("A veces");
        jPanel1.add(jLAVeces5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jLCasiNunca5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca5.setText("Casi nunca");
        jPanel1.add(jLCasiNunca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLNunca5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca5.setText("Nunca");
        jPanel1.add(jLNunca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jRBSiempre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        jRBCasiSiem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jRBAVeces5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        jRBCasiNunca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("6. Consumo poco azúcar, dulces, pastillas, chocolates, helados y otros alimentos con alto contenido de azúcar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLSiempre6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre6.setText("Siempre");
        jPanel1.add(jLSiempre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        jLCasiSiempre6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre6.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jLAVeces6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces6.setText("A veces");
        jPanel1.add(jLAVeces6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLCasiNunca6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca6.setText("Casi nunca");
        jPanel1.add(jLCasiNunca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jLNunca6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca6.setText("Nunca");
        jPanel1.add(jLNunca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        jRBSiempre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        jRBCasiSiem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        jRBAVeces6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        jRBCasiNunca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setText("7. Consumo diariamente frutas y vegetales.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLSiempre7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre7.setText("Siempre");
        jPanel1.add(jLSiempre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        jLCasiSiempre7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre7.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, -1, -1));

        jLAVeces7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces7.setText("A veces");
        jPanel1.add(jLAVeces7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, -1, -1));

        jLCasiNunca7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca7.setText("Casi nunca");
        jPanel1.add(jLCasiNunca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, -1, -1));

        jLNunca7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca7.setText("Nunca");
        jPanel1.add(jLNunca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, -1, -1));

        jRBSiempre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, -1, -1));

        jRBCasiSiem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, -1));

        jRBAVeces7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, -1, -1));

        jRBCasiNunca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, -1, -1));

        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setText("8. Tomo por lo menos 8 vasos de agua al día.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));

        jLSiempre8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre8.setText("Siempre");
        jPanel1.add(jLSiempre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, -1));

        jLCasiSiempre8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre8.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 720, -1, -1));

        jLAVeces8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces8.setText("A veces");
        jPanel1.add(jLAVeces8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, -1, -1));

        jLCasiNunca8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca8.setText("Casi nunca");
        jPanel1.add(jLCasiNunca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, -1, -1));

        jLNunca8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca8.setText("Nunca");
        jPanel1.add(jLNunca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, -1, -1));

        jRBSiempre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 740, -1, -1));

        jRBCasiSiem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, -1, -1));

        jRBAVeces8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 740, -1, -1));

        jRBCasiNunca7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, -1, -1));

        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 740, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setText("9. Considero que mantengo un peso saludable, sin exceso de barriga");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, -1));

        jLSiempre9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre9.setText("Siempre");
        jPanel1.add(jLSiempre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, -1, -1));

        jLCasiSiempre9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre9.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 800, -1, -1));

        jLAVeces9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces9.setText("A veces");
        jPanel1.add(jLAVeces9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 800, -1, -1));

        jLCasiNunca9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca9.setText("Casi nunca");
        jPanel1.add(jLCasiNunca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 800, -1, -1));

        jLNunca9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca9.setText("Nunca");
        jPanel1.add(jLNunca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 800, -1, -1));

        jRBSiempre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 820, -1, -1));

        jRBCasiSiem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 820, -1, -1));

        jRBAVeces9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 820, -1, -1));

        jRBCasiNunca8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 820, -1, -1));

        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 820, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setText("10. Realizo todos los días 30 minutos de actividad física tales como: caminar, correr,trabajo en la casa o campo,");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setText("hacer el jardín, bailar, subir lomas o escaleras y/o deportes.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 870, -1, -1));

        jLSiempre10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLSiempre10.setText("Siempre");
        jPanel1.add(jLSiempre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 900, -1, -1));

        jLCasiSiempre10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiSiempre10.setText("Casi siempre");
        jPanel1.add(jLCasiSiempre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 900, -1, -1));

        jLAVeces10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLAVeces10.setText("A veces");
        jPanel1.add(jLAVeces10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 900, -1, -1));

        jLCasiNunca10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLCasiNunca10.setText("Casi nunca");
        jPanel1.add(jLCasiNunca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 900, -1, -1));

        jLNunca10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLNunca10.setText("Nunca");
        jPanel1.add(jLNunca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 900, -1, -1));

        jRBSiempre10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSiempre10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBSiempre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 920, -1, -1));

        jRBCasiSiem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiSiem10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiSiem10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 920, -1, -1));

        jRBAVeces10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAVeces10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAVeces10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 920, -1, -1));

        jRBCasiNunca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCasiNunca9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCasiNunca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 920, -1, -1));

        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 920, -1, -1));

        jLRespuesta.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jPanel1.add(jLRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setText(" frascos y cajeta.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jButton1.setText("INGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 970, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoExt.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 1100));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBSiempre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre2ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre2.isSelected()){
            jRBCasiSiem2.setSelected(false);
            jRBAVeces2.setSelected(false);
            jRBCasiNunca2.setSelected(false);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre2ActionPerformed

    private void jRBSiempre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre1ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre1.isSelected()){
            jRBCasiSiem1.setSelected(false);
            jRBAVeces1.setSelected(false);
            jRBCasiNunca.setSelected(false);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre1ActionPerformed

    private void jRBSiempre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre3ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre3.isSelected()){
            jRBCasiSiem3.setSelected(false);
            jRBAVeces3.setSelected(false);
            jRBCasiNunca2.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre3ActionPerformed

    private void jRBSiempre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre4ActionPerformed
        if (jRBSiempre4.isSelected()){
            jRBCasiSiem4.setSelected(false);
            jRBAVeces4.setSelected(false);
            jRBCasiNunca3.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre4ActionPerformed

    private void jRBSiempre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre5ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre5.isSelected()){
            jRBCasiSiem5.setSelected(false);
            jRBAVeces5.setSelected(false);
            jRBCasiNunca4.setSelected(false);
            jRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre5ActionPerformed

    private void jRBSiempre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre6ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre6.isSelected()){
            jRBCasiSiem6.setSelected(false);
            jRBAVeces6.setSelected(false);
            jRBCasiNunca5.setSelected(false);
            jRadioButton6.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre6ActionPerformed

    private void jRBSiempre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre7ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre7.isSelected()){
            jRBCasiSiem7.setSelected(false);
            jRBAVeces7.setSelected(false);
            jRBCasiNunca6.setSelected(false);
            jRadioButton7.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre7ActionPerformed

    private void jRBSiempre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre8ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre8.isSelected()){
            jRBCasiSiem8.setSelected(false);
            jRBAVeces8.setSelected(false);
            jRBCasiNunca7.setSelected(false);
            jRadioButton8.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre8ActionPerformed

    private void jRBSiempre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre9ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre9.isSelected()){
            jRBCasiSiem9.setSelected(false);
            jRBAVeces9.setSelected(false);
            jRBCasiNunca8.setSelected(false);
            jRadioButton9.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre9ActionPerformed

    private void jRBSiempre10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSiempre10ActionPerformed
        // TODO add your handling code here:
        if (jRBSiempre10.isSelected()){
            jRBCasiSiem10.setSelected(false);
            jRBAVeces10.setSelected(false);
            jRBCasiNunca9.setSelected(false);
            jRadioButton10.setSelected(false);
        }
    }//GEN-LAST:event_jRBSiempre10ActionPerformed

    private void jRBCasiSiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem1ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem1.isSelected()){
            jRBSiempre1.setSelected(false);
            jRBAVeces1.setSelected(false);
            jRBCasiNunca.setSelected(false);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem1ActionPerformed

    private void jRBCasiSiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem2ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem2.isSelected()){
            jRBSiempre2.setSelected(false);
            jRBAVeces2.setSelected(false);
            jRBCasiNunca1.setSelected(false);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem2ActionPerformed

    private void jRBCasiSiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem3ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem3.isSelected()){
            jRBSiempre3.setSelected(false);
            jRBAVeces3.setSelected(false);
            jRBCasiNunca2.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem3ActionPerformed

    private void jRBCasiSiem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem4ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem4.isSelected()){
            jRBSiempre4.setSelected(false);
            jRBAVeces4.setSelected(false);
            jRBCasiNunca3.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem4ActionPerformed

    private void jRBCasiSiem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem5ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem5.isSelected()){
            jRBSiempre5.setSelected(false);
            jRBAVeces5.setSelected(false);
            jRBCasiNunca4.setSelected(false);
            jRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem5ActionPerformed

    private void jRBCasiSiem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem6ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem6.isSelected()){
            jRBSiempre6.setSelected(false);
            jRBAVeces6.setSelected(false);
            jRBCasiNunca5.setSelected(false);
            jRadioButton6.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem6ActionPerformed

    private void jRBCasiSiem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem7ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem7.isSelected()){
            jRBSiempre7.setSelected(false);
            jRBAVeces7.setSelected(false);
            jRBCasiNunca6.setSelected(false);
            jRadioButton7.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem7ActionPerformed

    private void jRBCasiSiem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem8ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem8.isSelected()){
            jRBSiempre8.setSelected(false);
            jRBAVeces8.setSelected(false);
            jRBCasiNunca7.setSelected(false);
            jRadioButton8.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem8ActionPerformed

    private void jRBCasiSiem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem9ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem9.isSelected()){
            jRBSiempre9.setSelected(false);
            jRBAVeces9.setSelected(false);
            jRBCasiNunca8.setSelected(false);
            jRadioButton9.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem9ActionPerformed

    private void jRBCasiSiem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiSiem10ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiSiem10.isSelected()){
            jRBSiempre10.setSelected(false);
            jRBAVeces10.setSelected(false);
            jRBCasiNunca9.setSelected(false);
            jRadioButton10.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiSiem10ActionPerformed

    private void jRBAVeces1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces1ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces1.isSelected()){
            jRBSiempre1.setSelected(false);
            jRBCasiSiem1.setSelected(false);
            jRBCasiNunca.setSelected(false);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces1ActionPerformed

    private void jRBAVeces2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces2ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces2.isSelected()){
            jRBSiempre2.setSelected(false);
            jRBCasiSiem2.setSelected(false);
            jRBCasiNunca1.setSelected(false);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces2ActionPerformed

    private void jRBAVeces3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces3ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces3.isSelected()){
            jRBSiempre3.setSelected(false);
            jRBCasiSiem3.setSelected(false);
            jRBCasiNunca2.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces3ActionPerformed

    private void jRBAVeces4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces4ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces4.isSelected()){
            jRBSiempre4.setSelected(false);
            jRBCasiSiem4.setSelected(false);
            jRBCasiNunca3.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces4ActionPerformed

    private void jRBAVeces5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces5ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces5.isSelected()){
            jRBSiempre5.setSelected(false);
            jRBCasiSiem5.setSelected(false);
            jRBCasiNunca4.setSelected(false);
            jRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces5ActionPerformed

    private void jRBAVeces6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces6ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces6.isSelected()){
            jRBSiempre6.setSelected(false);
            jRBCasiSiem6.setSelected(false);
            jRBCasiNunca5.setSelected(false);
            jRadioButton6.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces6ActionPerformed

    private void jRBAVeces7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces7ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces7.isSelected()){
            jRBSiempre7.setSelected(false);
            jRBCasiSiem7.setSelected(false);
            jRBCasiNunca6.setSelected(false);
            jRadioButton7.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces7ActionPerformed

    private void jRBAVeces8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces8ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces8.isSelected()){
            jRBSiempre8.setSelected(false);
            jRBCasiSiem8.setSelected(false);
            jRBCasiNunca7.setSelected(false);
            jRadioButton8.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces8ActionPerformed

    private void jRBAVeces9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces9ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces9.isSelected()){
            jRBSiempre9.setSelected(false);
            jRBCasiSiem9.setSelected(false);
            jRBCasiNunca8.setSelected(false);
            jRadioButton9.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces9ActionPerformed

    private void jRBAVeces10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAVeces10ActionPerformed
        // TODO add your handling code here:
        if (jRBAVeces10.isSelected()){
            jRBSiempre10.setSelected(false);
            jRBCasiSiem10.setSelected(false);
            jRBCasiNunca9.setSelected(false);
            jRadioButton10.setSelected(false);
        }
    }//GEN-LAST:event_jRBAVeces10ActionPerformed

    private void jRBCasiNuncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNuncaActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca.isSelected()){
            jRBSiempre1.setSelected(false);
            jRBCasiSiem1.setSelected(false);
            jRBAVeces1.setSelected(false);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNuncaActionPerformed

    private void jRBCasiNunca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca1ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca1.isSelected()){
            jRBSiempre2.setSelected(false);
            jRBCasiSiem2.setSelected(false);
            jRBAVeces2.setSelected(false);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca1ActionPerformed

    private void jRBCasiNunca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca2ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca2.isSelected()){
            jRBSiempre3.setSelected(false);
            jRBCasiSiem3.setSelected(false);
            jRBAVeces3.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca2ActionPerformed

    private void jRBCasiNunca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca3ActionPerformed
        if (jRBCasiNunca3.isSelected()){
            jRBSiempre4.setSelected(false);
            jRBCasiSiem4.setSelected(false);
            jRBAVeces4.setSelected(false);
            jRadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca3ActionPerformed

    private void jRBCasiNunca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca4ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca4.isSelected()){
            jRBSiempre5.setSelected(false);
            jRBCasiSiem5.setSelected(false);
            jRBAVeces5.setSelected(false);
            jRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca4ActionPerformed

    private void jRBCasiNunca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca5ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca5.isSelected()){
            jRBSiempre6.setSelected(false);
            jRBCasiSiem6.setSelected(false);
            jRBAVeces6.setSelected(false);
            jRadioButton6.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca5ActionPerformed

    private void jRBCasiNunca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca6ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca6.isSelected()){
            jRBSiempre7.setSelected(false);
            jRBCasiSiem7.setSelected(false);
            jRBAVeces7.setSelected(false);
            jRadioButton7.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca6ActionPerformed

    private void jRBCasiNunca7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca7ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca7.isSelected()){
            jRBSiempre8.setSelected(false);
            jRBCasiSiem8.setSelected(false);
            jRBAVeces8.setSelected(false);
            jRadioButton8.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca7ActionPerformed

    private void jRBCasiNunca8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca8ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca8.isSelected()){
            jRBSiempre9.setSelected(false);
            jRBCasiSiem9.setSelected(false);
            jRBAVeces9.setSelected(false);
            jRadioButton9.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca8ActionPerformed

    private void jRBCasiNunca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCasiNunca9ActionPerformed
        // TODO add your handling code here:
        if (jRBCasiNunca9.isSelected()){
            jRBSiempre10.setSelected(false);
            jRBCasiSiem10.setSelected(false);
            jRBAVeces10.setSelected(false);
            jRadioButton10.setSelected(false);
        }
    }//GEN-LAST:event_jRBCasiNunca9ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()){
            jRBSiempre1.setSelected(false);
            jRBCasiSiem1.setSelected(false);
            jRBAVeces1.setSelected(false);
            jRBCasiNunca.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()){
            jRBSiempre2.setSelected(false);
            jRBCasiSiem2.setSelected(false);
            jRBAVeces2.setSelected(false);
            jRBCasiNunca1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()){
            jRBSiempre3.setSelected(false);
            jRBCasiSiem3.setSelected(false);
            jRBAVeces3.setSelected(false);
            jRBCasiNunca2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()){
            jRBSiempre4.setSelected(false);
            jRBCasiSiem4.setSelected(false);
            jRBAVeces4.setSelected(false);
            jRBCasiNunca3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton5.isSelected()){
            jRBSiempre5.setSelected(false);
            jRBCasiSiem5.setSelected(false);
            jRBAVeces5.setSelected(false);
            jRBCasiNunca4.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton6.isSelected()){
            jRBSiempre6.setSelected(false);
            jRBCasiSiem6.setSelected(false);
            jRBAVeces6.setSelected(false);
            jRBCasiNunca5.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton7.isSelected()){
            jRBSiempre7.setSelected(false);
            jRBCasiSiem7.setSelected(false);
            jRBAVeces7.setSelected(false);
            jRBCasiNunca6.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton8.isSelected()){
            jRBSiempre8.setSelected(false);
            jRBCasiSiem8.setSelected(false);
            jRBAVeces8.setSelected(false);
            jRBCasiNunca7.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton9.isSelected()){
            jRBSiempre9.setSelected(false);
            jRBCasiSiem9.setSelected(false);
            jRBAVeces9.setSelected(false);
            jRBCasiNunca8.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton10.isSelected()){
            jRBSiempre10.setSelected(false);
            jRBCasiSiem10.setSelected(false);
            jRBAVeces10.setSelected(false);
            jRBCasiNunca9.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Coneccion con = null;
        try {
            con = new Coneccion();
        } catch (CLIPSLoadException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        con.getClips();
        try{
            theRouter = new CaptureRouter(con.getClips(),new String [] { Router.STDOUT, 
                                                       Router.STDERR,
                                                       Router.STDWRN } );
            con.getClips().reset();
            con.getClips().eval("(assert (respuetas (preg1 "+primeraPre()+") (preg2 "+segundaPre()+") (preg3 "+terceraPre()+") (preg4 "+cuartaPre()+") (preg5 "+quintaPre()+") (preg6 "+sextaPre()+") (preg7 "+septimaPre()+") (preg8 "+octavaPre()+") (preg9 "+novenaPre()+") (preg10 "+decimaPre()+") ))");
            con.getClips().run();
            String respuesta=theRouter.getOutput();
            jLRespuesta.setText(respuesta);
            //System.out.println("Output: " + theRouter.getOutput());
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    public int primeraPre (){
        r1=0;
        if(jRBSiempre1.isSelected()){
            r1=5;
        }
        if(jRBCasiSiem1.isSelected()){
            r1=4;
        }
        if(jRBAVeces1.isSelected()){
            r1=3;
        }
        if(jRBCasiNunca.isSelected()){
            r1=1;
        }
        if(jRadioButton1.isSelected()){
            r1=0;
        }
        return r1;
    }
    
    public int segundaPre (){
        r2=0;
        if(jRBSiempre2.isSelected()){
            r2=5;
        }
        if(jRBCasiSiem2.isSelected()){
            r2=4;
        }
        if(jRBAVeces2.isSelected()){
            r2=3;
        }
        if(jRBCasiNunca1.isSelected()){
            r2=1;
        }
        if(jRadioButton2.isSelected()){
            r2=0;
        }
        return r2;
    }
    
    public int terceraPre (){
        r3=0;
        if(jRBSiempre3.isSelected()){
            r3=5;
        }
        if(jRBCasiSiem3.isSelected()){
            r3=4;
        }
        if(jRBAVeces3.isSelected()){
            r3=3;
        }
        if(jRBCasiNunca2.isSelected()){
            r3=1;
        }
        if(jRadioButton3.isSelected()){
            r3=0;
        }
        return r3;
    }
    
    public int cuartaPre (){
        r4=0;
        if(jRBSiempre4.isSelected()){
            r4=5;
        }
        if(jRBCasiSiem4.isSelected()){
            r4=4;
        }
        if(jRBAVeces4.isSelected()){
            r4=3;
        }
        if(jRBCasiNunca3.isSelected()){
            r4=1;
        }
        if(jRadioButton4.isSelected()){
            r4=0;
        }
        return r4;
    }
    
    public int quintaPre (){
        r5=0;
        if(jRBSiempre5.isSelected()){
            r5=5;
        }
        if(jRBCasiSiem5.isSelected()){
            r5=4;
        }
        if(jRBAVeces5.isSelected()){
            r5=3;
        }
        if(jRBCasiNunca4.isSelected()){
            r5=1;
        }
        if(jRadioButton5.isSelected()){
            r5=0;
        }
        return r5;
    }
    
    public int sextaPre (){
        r6=0;
        if(jRBSiempre6.isSelected()){
            r6=5;
        }
        if(jRBCasiSiem6.isSelected()){
            r6=4;
        }
        if(jRBAVeces6.isSelected()){
            r6=3;
        }
        if(jRBCasiNunca5.isSelected()){
            r6=1;
        }
        if(jRadioButton6.isSelected()){
            r6=0;
        }
        return r6;
    }
    
    public int septimaPre (){
        r7=0;
        if(jRBSiempre7.isSelected()){
            r7=5;
        }
        if(jRBCasiSiem7.isSelected()){
            r7=4;
        }
        if(jRBAVeces7.isSelected()){
            r7=3;
        }
        if(jRBCasiNunca6.isSelected()){
            r7=1;
        }
        if(jRadioButton7.isSelected()){
            r7=0;
        }
        return r7;
    }
    
    public int octavaPre (){
        r8=0;
        if(jRBSiempre8.isSelected()){
            r8=5;
        }
        if(jRBCasiSiem8.isSelected()){
            r8=4;
        }
        if(jRBAVeces8.isSelected()){
            r8=3;
        }
        if(jRBCasiNunca7.isSelected()){
            r8=1;
        }
        if(jRadioButton8.isSelected()){
            r8=0;
        }
        return r9;
    }
    
    public int novenaPre (){
        r9=0;
        if(jRBSiempre9.isSelected()){
            r9=5;
        }
        if(jRBCasiSiem9.isSelected()){
            r9=4;
        }
        if(jRBAVeces9.isSelected()){
            r9=3;
        }
        if(jRBCasiNunca8.isSelected()){
            r8=1;
        }
        if(jRadioButton9.isSelected()){
            r9=0;
        }
        return r9;
    }
    
    public int decimaPre (){
        r10=0;
        if(jRBSiempre10.isSelected()){
            r10=5;
        }
        if(jRBCasiSiem10.isSelected()){
            r10=4;
        }
        if(jRBAVeces10.isSelected()){
            r10=3;
        }
        if(jRBCasiNunca9.isSelected()){
            r10=1;
        }
        if(jRadioButton10.isSelected()){
            r10=0;
        }
        return r10;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAVeces1;
    private javax.swing.JLabel jLAVeces10;
    private javax.swing.JLabel jLAVeces2;
    private javax.swing.JLabel jLAVeces3;
    private javax.swing.JLabel jLAVeces4;
    private javax.swing.JLabel jLAVeces5;
    private javax.swing.JLabel jLAVeces6;
    private javax.swing.JLabel jLAVeces7;
    private javax.swing.JLabel jLAVeces8;
    private javax.swing.JLabel jLAVeces9;
    private javax.swing.JLabel jLCasiNunca1;
    private javax.swing.JLabel jLCasiNunca10;
    private javax.swing.JLabel jLCasiNunca2;
    private javax.swing.JLabel jLCasiNunca3;
    private javax.swing.JLabel jLCasiNunca4;
    private javax.swing.JLabel jLCasiNunca5;
    private javax.swing.JLabel jLCasiNunca6;
    private javax.swing.JLabel jLCasiNunca7;
    private javax.swing.JLabel jLCasiNunca8;
    private javax.swing.JLabel jLCasiNunca9;
    private javax.swing.JLabel jLCasiSiempre1;
    private javax.swing.JLabel jLCasiSiempre10;
    private javax.swing.JLabel jLCasiSiempre2;
    private javax.swing.JLabel jLCasiSiempre3;
    private javax.swing.JLabel jLCasiSiempre4;
    private javax.swing.JLabel jLCasiSiempre5;
    private javax.swing.JLabel jLCasiSiempre6;
    private javax.swing.JLabel jLCasiSiempre7;
    private javax.swing.JLabel jLCasiSiempre8;
    private javax.swing.JLabel jLCasiSiempre9;
    private javax.swing.JLabel jLNunca1;
    private javax.swing.JLabel jLNunca10;
    private javax.swing.JLabel jLNunca2;
    private javax.swing.JLabel jLNunca3;
    private javax.swing.JLabel jLNunca4;
    private javax.swing.JLabel jLNunca5;
    private javax.swing.JLabel jLNunca6;
    private javax.swing.JLabel jLNunca7;
    private javax.swing.JLabel jLNunca8;
    private javax.swing.JLabel jLNunca9;
    private javax.swing.JLabel jLRespuesta;
    private javax.swing.JLabel jLSiempre1;
    private javax.swing.JLabel jLSiempre10;
    private javax.swing.JLabel jLSiempre2;
    private javax.swing.JLabel jLSiempre3;
    private javax.swing.JLabel jLSiempre4;
    private javax.swing.JLabel jLSiempre5;
    private javax.swing.JLabel jLSiempre6;
    private javax.swing.JLabel jLSiempre7;
    private javax.swing.JLabel jLSiempre8;
    private javax.swing.JLabel jLSiempre9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBAVeces1;
    private javax.swing.JRadioButton jRBAVeces10;
    private javax.swing.JRadioButton jRBAVeces2;
    private javax.swing.JRadioButton jRBAVeces3;
    private javax.swing.JRadioButton jRBAVeces4;
    private javax.swing.JRadioButton jRBAVeces5;
    private javax.swing.JRadioButton jRBAVeces6;
    private javax.swing.JRadioButton jRBAVeces7;
    private javax.swing.JRadioButton jRBAVeces8;
    private javax.swing.JRadioButton jRBAVeces9;
    private javax.swing.JRadioButton jRBCasiNunca;
    private javax.swing.JRadioButton jRBCasiNunca1;
    private javax.swing.JRadioButton jRBCasiNunca2;
    private javax.swing.JRadioButton jRBCasiNunca3;
    private javax.swing.JRadioButton jRBCasiNunca4;
    private javax.swing.JRadioButton jRBCasiNunca5;
    private javax.swing.JRadioButton jRBCasiNunca6;
    private javax.swing.JRadioButton jRBCasiNunca7;
    private javax.swing.JRadioButton jRBCasiNunca8;
    private javax.swing.JRadioButton jRBCasiNunca9;
    private javax.swing.JRadioButton jRBCasiSiem1;
    private javax.swing.JRadioButton jRBCasiSiem10;
    private javax.swing.JRadioButton jRBCasiSiem2;
    private javax.swing.JRadioButton jRBCasiSiem3;
    private javax.swing.JRadioButton jRBCasiSiem4;
    private javax.swing.JRadioButton jRBCasiSiem5;
    private javax.swing.JRadioButton jRBCasiSiem6;
    private javax.swing.JRadioButton jRBCasiSiem7;
    private javax.swing.JRadioButton jRBCasiSiem8;
    private javax.swing.JRadioButton jRBCasiSiem9;
    private javax.swing.JRadioButton jRBSiempre1;
    private javax.swing.JRadioButton jRBSiempre10;
    private javax.swing.JRadioButton jRBSiempre2;
    private javax.swing.JRadioButton jRBSiempre3;
    private javax.swing.JRadioButton jRBSiempre4;
    private javax.swing.JRadioButton jRBSiempre5;
    private javax.swing.JRadioButton jRBSiempre6;
    private javax.swing.JRadioButton jRBSiempre7;
    private javax.swing.JRadioButton jRBSiempre8;
    private javax.swing.JRadioButton jRBSiempre9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

